/* eslint-disable @next/next/no-img-element */
"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, API_BASE_URL, FILE_BASE_URL, type Device, type Taxonomy } from "@/lib/api";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { HeroView, ValueStrip } from "@/components/views/HeroView";
import StoryView from "@/components/views/StoryView";
const API = API_BASE_URL;
type CartItem = Device & {quantity:number};

const Icon=({name,size=20}:{name:string;size?:number})=>{const p:Record<string,React.ReactNode>={search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,bag:<><path d="M6 8h12l1 13H5L6 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>,heart:<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5a5.5 5.5 0 0 0 1-8.9Z"/>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,arrow:<><path d="M5 12h14"/><path d="m14 7 5 5-5 5"/></>,close:<><path d="m6 6 12 12"/><path d="m18 6-12 12"/></>,minus:<path d="M5 12h14"/>,plus:<><path d="M5 12h14"/><path d="M12 5v14"/></>,star:<path d="m12 2 3.1 6.4 6.9 1-5 4.9 1.2 6.9-6.2-3.3-6.2 3.3L7 14.3l-5-4.9 6.9-1L12 2Z"/>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{p[name]}</svg>};
function ProductVisual({product,className=""}:{product:Device;className?:string}){const[failed,setFailed]=useState(false);return <div className={`product-visual ${className}`}>{product.img&&!failed?<img src={`${FILE_BASE_URL}/${product.img}`} alt={product.name} onError={()=>setFailed(true)}/>:<div className="product-monogram">{product.name.slice(0,2).toUpperCase()}</div>}</div>}

export default function Marketplace(){
 const[devices,setDevices]=useState<Device[]>([]),[brands,setBrands]=useState<Taxonomy[]>([]),[types,setTypes]=useState<Taxonomy[]>([]);const[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[brand,setBrand]=useState<number|null>(null),[type,setType]=useState<number|null>(null),[sort,setSort]=useState("featured"),[page,setPage]=useState(1),[count,setCount]=useState(0);const[selected,setSelected]=useState<Device|null>(null),[cartOpen,setCartOpen]=useState(false),[authOpen,setAuthOpen]=useState(false),[cart,setCart]=useState<CartItem[]>([]),[favorites,setFavorites]=useState<number[]>([]),[toast,setToast]=useState("");
 useEffect(()=>{Promise.resolve().then(()=>{try{setCart(JSON.parse(localStorage.getItem("atelier-cart")||"[]"));setFavorites(JSON.parse(localStorage.getItem("atelier-favorites")||"[]"))}catch{}});Promise.all([api.brands.list(),api.types.list()]).then(([b,t])=>{setBrands(b);setTypes(t)}).catch(()=>{})},[]);
 useEffect(()=>{queueMicrotask(()=>{setLoading(true);setError("")});api.devices.list({page,limit:9,brandId:brand||undefined,typeId:type||undefined}).then(d=>{setDevices(d.rows||[]);setCount(d.count||0)}).catch(()=>{setDevices([]);setCount(0);setError("We couldn’t reach the marketplace server. Check the API URL in your .env file and make sure the server is running.")}).finally(()=>setLoading(false))},[brand,type,page]);
 const shown=useMemo(()=>{const q=query.trim().toLowerCase(),r=devices.filter(d=>!q||d.name.toLowerCase().includes(q));return[...r].sort((a,b)=>sort==="price-low"?a.price-b.price:sort==="price-high"?b.price-a.price:sort==="rating"?(b.rating||0)-(a.rating||0):0)},[devices,query,sort]);
 const saveCart=(n:CartItem[])=>{setCart(n);localStorage.setItem("atelier-cart",JSON.stringify(n))};const addCart=(item:Device)=>{const f=cart.find(i=>i.id===item.id);saveCart(f?cart.map(i=>i.id===item.id?{...i,quantity:i.quantity+1}:i):[...cart,{...item,quantity:1}]);setToast(`${item.name} added to your bag`);setTimeout(()=>setToast(""),2400)};const toggleFavorite=(id:number)=>{const n=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(n);localStorage.setItem("atelier-favorites",JSON.stringify(n))};const cartCount=cart.reduce((n,i)=>n+i.quantity,0),total=cart.reduce((n,i)=>n+i.price*i.quantity,0);const clearFilters=()=>{setBrand(null);setType(null);setQuery("");setPage(1)};
 return <main><Header brands={brands} types={types} cartCount={cartCount} onBrandSelect={id=>{setBrand(id);setPage(1)}} onTypeSelect={id=>{setType(id);setPage(1)}} onAccountOpen={()=>setAuthOpen(true)} onCartOpen={()=>setCartOpen(true)}/>
 <HeroView/>
 <ValueStrip/>
 <section className="catalog" id="shop"><div className="section-heading"><div><p className="eyebrow">Shop all</p><h2>Designed to belong.</h2></div><p>{count} considered {count===1?"piece":"pieces"}, each selected for lasting quality.</p></div><div className="shop-tools"><div className="search-box"><Icon name="search" size={19}/><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the collection"/></div><div className="selects"><select aria-label="Filter by category" value={type||""} onChange={e=>{setType(e.target.value?+e.target.value:null);setPage(1)}}><option value="">All categories</option>{types.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select aria-label="Filter by brand" value={brand||""} onChange={e=>{setBrand(e.target.value?+e.target.value:null);setPage(1)}}><option value="">All makers</option>{brands.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="rating">Top rated</option></select></div></div>
 {(brand||type||query)&&<div className="active-filter"><span>Showing a refined selection</span><button onClick={clearFilters}>Clear filters <Icon name="close" size={14}/></button></div>}
 {loading?<div className="product-grid">{Array.from({length:6}).map((_,i)=><div className="skeleton" key={i}><div/><span/><small/></div>)}</div>:error?<div className="empty"><div>↗</div><h3>The collection is taking a moment</h3><p>{error}</p><button className="outline" onClick={()=>location.reload()}>Try again</button></div>:shown.length===0?<div className="empty"><h3>No pieces found</h3><p>Try another search or clear the current filters.</p><button className="outline" onClick={clearFilters}>View everything</button></div>:<div className="product-grid">{shown.map((product,index)=><article className="product-card" key={product.id}><button className={`favorite ${favorites.includes(product.id)?"active":""}`} onClick={()=>toggleFavorite(product.id)} aria-label="Save product"><Icon name="heart" size={19}/></button><button className="visual-button" onClick={()=>setSelected(product)}><ProductVisual product={product}/>{index<2&&<span className="tag">New</span>}</button><div className="product-meta"><div><p>{brands.find(b=>b.id===product.brandId)?.name||"Independent maker"}</p><h3><button onClick={()=>setSelected(product)}>{product.name}</button></h3></div><strong>${Number(product.price).toLocaleString()}</strong></div><div className="rating"><Icon name="star" size={13}/><span>{Number(product.rating||0).toFixed(1)}</span></div><button className="quick-add" onClick={()=>addCart(product)}>Add to bag <Icon name="plus" size={17}/></button></article>)}</div>}{count>9&&<div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {Math.ceil(count/9)}</span><button disabled={page>=Math.ceil(count/9)} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</section>
 <StoryView/>
 <Footer/>
 {toast&&<div className="toast">✓ {toast}</div>}{selected&&<ProductModal product={selected} brand={brands.find(b=>b.id===selected.brandId)?.name} close={()=>setSelected(null)} add={()=>{addCart(selected);setSelected(null)}}/>}{cartOpen&&<CartDrawer cart={cart} total={total} close={()=>setCartOpen(false)} update={(id,delta)=>saveCart(cart.map(i=>i.id===id?{...i,quantity:i.quantity+delta}:i).filter(i=>i.quantity>0))}/>} {authOpen&&<AuthModal close={()=>setAuthOpen(false)}/>}</main>}

function ProductModal({product,brand,close,add}:{product:Device;brand?:string;close:()=>void;add:()=>void}){const[detail,setDetail]=useState(product);useEffect(()=>{fetch(`${API}/device/${product.id}`).then(r=>r.ok?r.json():product).then(setDetail).catch(()=>{})},[product]);return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="product-modal"><button className="modal-close" onClick={close}><Icon name="close"/></button><ProductVisual product={product} className="modal-image"/><div className="modal-copy"><p className="eyebrow">{brand||"Independent maker"}</p><h2>{product.name}</h2><div className="modal-rating"><span><Icon name="star" size={15}/> {Number(product.rating||0).toFixed(1)}</span><strong>${Number(product.price).toLocaleString()}</strong></div><p className="modal-description">Purposeful technology with a refined presence, selected to make your everyday rituals feel a little more considered.</p>{detail.info&&detail.info.length>0&&<div className="specs">{detail.info.map((x,i)=><div key={x.id||i}><span>{x.title}</span><b>{x.description}</b></div>)}</div>}<button className="primary full" onClick={add}>Add to bag <Icon name="arrow" size={18}/></button><small>Complimentary delivery · 30-day returns</small></div></div></div>}
function CartDrawer({cart,total,close,update}:{cart:CartItem[];total:number;close:()=>void;update:(id:number,delta:number)=>void}){return <div className="overlay drawer-overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="drawer"><div className="drawer-head"><div><p className="eyebrow">Your selection</p><h2>Shopping bag</h2></div><button onClick={close}><Icon name="close"/></button></div>{cart.length===0?<div className="cart-empty"><Icon name="bag" size={34}/><h3>Your bag is beautifully empty</h3><p>Explore the collection and find something worth keeping.</p><button className="outline" onClick={close}>Continue shopping</button></div>:<><div className="cart-list">{cart.map(item=><div className="cart-item" key={item.id}><ProductVisual product={item}/><div><h3>{item.name}</h3><p>${Number(item.price).toLocaleString()}</p><div className="quantity"><button onClick={()=>update(item.id,-1)}><Icon name="minus" size={14}/></button><span>{item.quantity}</span><button onClick={()=>update(item.id,1)}><Icon name="plus" size={14}/></button></div></div><strong>${(item.price*item.quantity).toLocaleString()}</strong></div>)}</div><div className="cart-foot"><div><span>Subtotal</span><strong>${total.toLocaleString()}</strong></div><p>Delivery and taxes calculated at checkout.</p><button className="primary full">Continue to checkout <Icon name="arrow" size={18}/></button></div></>}</aside></div>}
function AuthModal({close}:{close:()=>void}){const[mode,setMode]=useState<"login"|"registration">("login"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const d=new FormData(e.currentTarget);try{const r=await fetch(`${API}/user/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:d.get("email"),password:d.get("password")})});const body=await r.json();if(!r.ok)throw new Error(body.message||"Please check your details.");localStorage.setItem("atelier-token",body.token);setMessage("Welcome to Atelier Market.");setTimeout(close,900)}catch(err){setMessage(err instanceof Error?err.message:"Something went wrong.")}finally{setBusy(false)}}return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="auth-modal"><button className="modal-close" onClick={close}><Icon name="close"/></button><p className="eyebrow">Your account</p><h2>{mode==="login"?"Welcome back.":"Join the atelier."}</h2><p>Save favorites and keep your considered finds close.</p><form onSubmit={submit}><label>Email address<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" minLength={6} required placeholder="At least 6 characters"/></label>{message&&<div className="form-message">{message}</div>}<button className="primary full" disabled={busy}>{busy?"One moment…":mode==="login"?"Sign in":"Create account"}</button></form><button className="switch-auth" onClick={()=>{setMode(mode==="login"?"registration":"login");setMessage("")}}>{mode==="login"?"New here? Create an account":"Already a member? Sign in"}</button></div></div>}
