"use client";

import { type FormEvent, useEffect, useState } from "react";
import { api, type CardPayload, type PendingOrder, type SavedCard } from "@/lib/api";
import type { CartItem } from "./CartDrawer";
import Icon from "@/components/ui/Icon";

type Props={cart:CartItem[];total:number;close:()=>void;onPaid:()=>void|Promise<void>};
const cardBrand=(number:string)=>number.startsWith("4")?"Visa":number.startsWith("5")?"Mastercard":"Card";

export default function CheckoutModal({cart,total,close,onPaid}:Props){
 const[cards,setCards]=useState<SavedCard[]>([]),[mode,setMode]=useState<"saved"|"new">("saved"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[pending,setPending]=useState<PendingOrder|null>(null),[saveAfterPayment,setSaveAfterPayment]=useState(false),[newCardMeta,setNewCardMeta]=useState<CardPayload|null>(null);
 const token=typeof window!=="undefined"?localStorage.getItem("atelier-token"):null;
 const items=cart.map(item=>({deviceId:item.id,quantity:item.quantity,price:Number(item.price)}));

 useEffect(()=>{if(!token){Promise.resolve().then(()=>{setMessage("Please sign in before checkout.");setLoading(false)});return}api.cards.list(token).then(setCards).catch(error=>setMessage(error instanceof Error?error.message:"Could not load cards")).finally(()=>setLoading(false))},[token]);

 const paySaved=async(cardId:number)=>{if(!token)return;setBusy(true);setMessage("");try{await api.orders.purchaseWithSavedCard({items,amount:total,cardId},token);await onPaid();setMessage("Payment successful. Thank you for your order!");setTimeout(close,1400)}catch(error){setMessage(error instanceof Error?error.message:"Payment failed")}finally{setBusy(false)}};
 const removeCard=async(id:number)=>{if(!token)return;setBusy(true);try{await api.cards.remove(id,token);setCards(current=>current.filter(card=>card.id!==id))}catch(error){setMessage(error instanceof Error?error.message:"Could not delete card")}finally{setBusy(false)}};
 const submitNew=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!token)return;const data=new FormData(event.currentTarget),number=String(data.get("number")||"").replace(/\D/g,""),expiryMonth=Number(data.get("expiryMonth")),expiryYear=Number(data.get("expiryYear")),holderName=String(data.get("holderName")||"");setBusy(true);setMessage("");try{const result=await api.orders.create({items,amount:total,card:{number,expiryMonth,expiryYear,password:String(data.get("password")||"")}},token);setPending(result);setNewCardMeta({holderName,brand:cardBrand(number),last4:number.slice(-4),expiryMonth,expiryYear,isDefault:cards.length===0})}catch(error){setMessage(error instanceof Error?error.message:"Payment failed")}finally{setBusy(false)}};
 const verify=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!token||!pending)return;const code=String(new FormData(event.currentTarget).get("code")||"");setBusy(true);setMessage("");try{await api.orders.verify({transactionId:pending.transactionId,verificationCode:code},token);if(saveAfterPayment&&newCardMeta){const saved=await api.cards.create(newCardMeta,token);setCards(current=>[saved,...current])}await onPaid();setMessage("Payment verified. Your order is complete!");setTimeout(close,1400)}catch(error){setMessage(error instanceof Error?error.message:"Verification failed")}finally{setBusy(false)}};

 return <div className="fixed inset-0 z-[80] grid place-items-center bg-[#181814]/70 p-4 backdrop-blur-sm" onMouseDown={event=>event.target===event.currentTarget&&close()}><div className="relative max-h-[92vh] w-full max-w-2xl overflow-auto rounded-[28px] bg-[#fbfaf6] p-6 shadow-2xl md:p-10"><button className="absolute top-5 right-5 grid h-10 w-10 place-items-center rounded-full bg-[#eee8db]" onClick={close}><Icon name="close"/></button><p className="mb-2 text-[9px] font-semibold uppercase tracking-[.22em] text-[#b95736]">Secure checkout</p><h2 className="font-serif text-4xl md:text-5xl">Complete your order.</h2><div className="my-6 flex justify-between rounded-2xl bg-[#eee8db] p-4 text-sm"><span>{cart.length} {cart.length===1?"item":"items"}</span><strong>${total.toLocaleString()}</strong></div>
 {pending?<Verification pending={pending} busy={busy} message={message} onSubmit={verify}/>:<><div className="mb-6 grid grid-cols-2 rounded-xl bg-[#eee8db] p-1"><button className={`rounded-lg py-2 text-[10px] uppercase tracking-[.12em] ${mode==="saved"?"bg-white shadow-sm":""}`} onClick={()=>setMode("saved")}>Saved cards</button><button className={`rounded-lg py-2 text-[10px] uppercase tracking-[.12em] ${mode==="new"?"bg-white shadow-sm":""}`} onClick={()=>setMode("new")}>New card</button></div>{loading?<p className="py-10 text-center text-sm text-[#716f67]">Loading cards…</p>:mode==="saved"?<div className="space-y-3">{cards.length?cards.map(card=><div key={card.id} className="flex items-center justify-between rounded-2xl border border-[#d8d2c5] p-4"><div><b className="font-serif text-lg">{card.brand} •••• {card.last4}</b><p className="mt-1 text-[10px] text-[#716f67]">{card.holderName} · {String(card.expiryMonth).padStart(2,"0")}/{card.expiryYear}{card.isDefault?" · Default":""}</p></div><div className="flex gap-2"><button disabled={busy} className="rounded-xl border border-[#d8d2c5] px-3 py-2 text-[9px] text-[#b95736]" onClick={()=>removeCard(card.id)}>Delete</button><button disabled={busy} className="rounded-xl bg-[#24241f] px-4 py-2 text-[9px] uppercase tracking-[.12em] !text-white" onClick={()=>paySaved(card.id)}>Pay</button></div></div>):<div className="py-10 text-center"><p className="font-serif text-xl">No saved cards yet.</p><button className="mt-3 text-xs text-[#b95736] underline" onClick={()=>setMode("new")}>Add a new card</button></div>}</div>:<NewCardForm busy={busy} save={saveAfterPayment} setSave={setSaveAfterPayment} onSubmit={submitNew}/>} {message&&<p className="mt-4 rounded-xl bg-[#f4e4de] p-3 text-center text-xs text-[#a34328]">{message}</p>}</>}
 <p className="mt-6 text-center text-[9px] leading-4 text-[#8a867d]">Development payment simulation. Full card details and passwords are never stored.</p></div></div>;
}

function NewCardForm({busy,save,setSave,onSubmit}:{busy:boolean;save:boolean;setSave:(v:boolean)=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="grid gap-4 sm:grid-cols-2" onSubmit={onSubmit}><Field label="Cardholder name" name="holderName" placeholder="Alice Example"/><div className="sm:col-span-2"><Field label="Card number" name="number" placeholder="4242 4242 4242 4242" inputMode="numeric"/></div><Field label="Expiry month" name="expiryMonth" placeholder="12" inputMode="numeric"/><Field label="Expiry year" name="expiryYear" placeholder="2030" inputMode="numeric"/><div className="sm:col-span-2"><Field label="Card password" name="password" type="password" placeholder="Payment password"/></div><label className="flex items-center gap-2 text-xs text-[#716f67] sm:col-span-2"><input type="checkbox" checked={save} onChange={e=>setSave(e.target.checked)}/> Save card display details for future purchases</label><button disabled={busy} className="primary full sm:col-span-2">{busy?"Processing…":"Continue to verification"}<Icon name="arrow" size={18}/></button></form>}
function Field({label,...props}:{label:string;name:string;placeholder:string;type?:string;inputMode?:"numeric"}){return <label className="text-[9px] uppercase tracking-[.12em]">{label}<input {...props} required className="mt-2 w-full rounded-xl border border-[#d8d2c5] bg-white px-4 py-3 text-xs normal-case tracking-normal outline-none focus:border-[#b95736]"/></label>}
function Verification({pending,busy,message,onSubmit}:{pending:PendingOrder;busy:boolean;message:string;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit} className="py-4 text-center"><div className="mx-auto mb-5 grid h-14 w-14 place-items-center rounded-full bg-[#e3eadf] text-2xl text-[#56704f]">✓</div><h3 className="font-serif text-2xl">Verify your payment</h3><p className="mt-2 text-xs text-[#716f67]">Enter the six-digit verification code. Development code: <b className="text-[#b95736]">{pending.verificationCode}</b></p><input name="code" required inputMode="numeric" maxLength={6} className="mx-auto mt-6 block w-48 rounded-xl border border-[#d8d2c5] bg-white px-4 py-3 text-center text-xl tracking-[.35em] outline-none focus:border-[#b95736]" placeholder="000000"/><button disabled={busy} className="primary mt-5">{busy?"Verifying…":"Verify and pay"}</button>{message&&<p className="mt-4 text-xs text-[#b95736]">{message}</p>}</form>}
