"use client";
import Link from "next/link";
import type { Taxonomy,User } from "@/lib/api";
import { localizedPath,useI18n } from "@/lib/i18n";
import LanguageSwitcher from "./LanguageSwitcher";

type Props={brands:Taxonomy[];types:Taxonomy[];cartCount:number;user:User|null;onAccountOpen:()=>void;onCartOpen:()=>void;onLogout:()=>void};
function HeaderIcon({name}:{name:"search"|"user"|"bag"}){const paths={search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,bag:<><path d="M6 8h12l1 13H5L6 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>}

export default function Header({brands,types,cartCount,user,onAccountOpen,onCartOpen,onLogout}:Props){const{locale,t}=useI18n();return <><div className="flex h-8 items-center justify-center gap-5 bg-[#24241f] text-[10px] uppercase tracking-[.09em] text-[#f8f3e9]">Complimentary delivery on orders over $150 <span className="hidden text-[#d8c8ad] sm:inline">Explore the edit →</span></div><header className="sticky top-0 z-20 flex h-[88px] items-center justify-between border-b border-[#d8d2c5] bg-[#fbfaf6]/95 px-[5.5vw] backdrop-blur-xl"><Link href={localizedPath(locale,"/")} className="flex flex-col font-serif text-[22px] font-semibold leading-[.73] tracking-[.08em]">ATELIER<span className="mt-2 font-sans text-[7px] tracking-[.36em]">MARKET</span></Link><nav className="hidden h-full items-center gap-9 text-xs lg:flex"><a className="hover:text-[#b95736]" href="#shop">{t.newArrivals}</a><Menu label={t.brands} title={t.shopByMaker} empty={t.noBrands} items={brands} href={id=>localizedPath(locale,`/brands/${id}`)}/><Menu label={t.categories} title={t.shopByCategory} empty={t.noCategories} items={types} href={id=>localizedPath(locale,`/types/${id}`)}/><a className="hover:text-[#b95736]" href="#story">{t.story}</a></nav><div className="flex items-center gap-2 sm:gap-4"><LanguageSwitcher/><button className="p-1" aria-label="Search" onClick={()=>document.getElementById("search")?.focus()}><HeaderIcon name="search"/></button>{user?<UserMenu user={user} onLogout={onLogout}/>:<button className="p-1" aria-label="Sign in" onClick={onAccountOpen}><HeaderIcon name="user"/></button>}<button className="flex items-center gap-1 p-1" aria-label="Shopping bag" onClick={onCartOpen}><HeaderIcon name="bag"/><b className="grid min-h-[17px] min-w-[17px] place-items-center rounded-full bg-[#b95736] px-1 text-[9px] text-white">{cartCount}</b></button></div></header></>}

function UserMenu({user,onLogout}:{user:User;onLogout:()=>void}){return <div className="group relative flex h-full items-center"><button className="flex items-center gap-2 rounded-full border border-[#d8d2c5] bg-white/60 py-1.5 pr-3 pl-1.5 hover:border-[#b95736]"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#b95736] text-[11px] font-semibold text-white">{user.email.charAt(0).toUpperCase()}</span><span className="hidden max-w-28 truncate text-[10px] sm:block">{user.email}</span></button><div className="invisible absolute top-[68px] right-0 w-64 translate-y-2 rounded-2xl border border-[#d8d2c5] bg-[#fbfaf6] p-4 opacity-0 shadow-xl transition-all group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"><div className="mb-3 flex items-center gap-3 border-b border-[#d8d2c5] pb-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#b95736] font-serif text-lg text-white">{user.email.charAt(0).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-xs font-medium">{user.email}</p><span className="text-[9px] uppercase tracking-[.14em] text-[#b95736]">{user.role}</span></div></div><div className="grid grid-cols-2 gap-2 text-[9px] text-[#716f67]"><span>User ID</span><b className="text-right text-[#24241f]">#{user.id}</b><span>Member since</span><b className="text-right text-[#24241f]">{new Date(user.createdAt).toLocaleDateString()}</b></div><button onClick={onLogout} className="mt-4 w-full rounded-xl border border-[#d8d2c5] py-2 text-[9px] uppercase tracking-[.14em] hover:border-[#b95736] hover:text-[#b95736]">Sign out</button></div></div>}
function Menu({label,title,empty,items,href}:{label:string;title:string;empty:string;items:Taxonomy[];href:(id:number)=>string}){return <div className="group relative flex h-full items-center"><button className="flex items-center gap-2">{label}<span className="text-[#b95736]">⌄</span></button><div className="invisible absolute top-[75px] left-1/2 w-[230px] -translate-x-1/2 translate-y-2 rounded-2xl border border-[#d8d2c5] bg-[#fbfaf6] p-5 opacity-0 shadow-xl transition-all group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"><p className="mb-3 border-b border-[#d8d2c5] pb-2 text-[8px] uppercase tracking-[.16em] text-[#b95736]">{title}</p>{items.length?items.map(item=><Link className="flex justify-between py-2 font-serif text-base transition-all hover:pl-1 hover:text-[#b95736]" key={item.id} href={href(item.id)}>{item.name}<span className="font-sans text-xs">→</span></Link>):<small className="block py-2 text-[#716f67]">{empty}</small>}</div></div>}
